feat(changelog): Add CHANGELOG linting during the PR
Signed-off-by: Marco Bulgarini <marco.bulgarini@gmail.com>

diff --git a/.github/workflows/semantic-checks.yaml b/.github/workflows/semantic-checks.yaml
--- a/.github/workflows/semantic-checks.yaml
+++ b/.github/workflows/semantic-checks.yaml
@@ -13,8 +13,6 @@ on:
       - docs/**
       - "*"
 jobs:
-  # TODO: add
-  # check we have at least a changelog fragment
   fetch-tag-info:
     runs-on: ubuntu-latest
     outputs:
@@ -34,7 +32,7 @@ jobs:
         uses: mikefarah/yq@v4.33.3
         with:
           cmd: yq '.version' 'galaxy.yml'
-  verify-tag-collision:
+  verify-tag-config-collision:
     runs-on: ubuntu-latest
     needs: [fetch-tag-info]
     steps:
@@ -50,12 +48,6 @@ jobs:
             echo "::notice ::Next tag is not present in git, proceeding."
             exit 0
           fi
-  verify-tag-config:
-    runs-on: ubuntu-latest
-    needs: [fetch-tag-info]
-    steps:
-      - name: Checkout the repo
-        uses: actions/checkout@v3
       - name: Check that next tag is configured in the Ansible Collection
         run: |
           git fetch --all --tags >/dev/null 2>&1
@@ -66,3 +58,30 @@ jobs:
             echo "::error ::Next tag is not configured in the Ansible Collection"
             exit 1
           fi
+  check-changelog-update:
+    runs-on: ubuntu-latest
+    needs: [fetch-tag-info]
+    steps:
+      - name: Checkout the repo
+        uses: actions/checkout@v3
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+          cache: pip
+      - name: Install antsibull-changelog
+        run: pip install antsibull-changelog==0.20.0
+      - name: Lint the CHANGELOG
+        run: antsibull-changelog linit
+      - name: Get added fragments
+        id: added-fragments
+        uses: tj-actions/changed-files@v35.9.0
+        with:
+          files: |
+            changelog/fragments/*.mdown
+            changelog/fragments/*.md
+      - name: Fail if there's no added fragments
+        if: ${{ steps.added-fragments.outputs.any_changed }} != 'true'
+        run: |
+          echo "::error ::No added fragments, won't create a meaningful CHANGELOG"
+          exit 1
